export const GET_POKEMONS = 'GET_POKEMONS';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const POKEMONS_LOAD = 'POKEMONS_LOAD';
export const POKEMON_LOAD = 'POKEMON_LOAD';
export const LOADER_DISPLAY_ON = 'LOADER_DISPLAY_ON';
export const LOADER_DISPLAY_OFF = 'LOADER_DISPLAY_OFF';
